### ISSUE TITLE
Metadata 'no description' string ought to be customizable

### ISSUE THREAD

**Issue by Grammostola** [Eskilstuna-kommun/layermanager-csw#21]
Currently if a metadata record has an empty or "missing" abstract it is shown in the Layeradder search pane with the hardcoded string "no description". This could be a user definable string in index.html where the plugin is initialized, together with other user definable strings like noSearchResultText

**Comment by PCunvik** [comment]
Solved by #41 and #43

**Comment by PCunvik** [comment]
Solved by #41 and #43
